version: '3'
services:
  udagram-reverseproxy:
    image: localhost:5000/reverseproxy
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend-user
      - backend-feed

  backend-user:
    image: localhost:5000/udagram-api-user
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: abcd1234
      POSTGRES_DB: postgres
      POSTGRES_HOST: localhost:5432
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      AWS_BUCKET: udagram-bucket-1234567
      JWT_SECRET: testing
      URL: 'http://localhost:8100'

  backend-feed:
    image: localhost:5000/udagram-api-feed

    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: abcd1234
      POSTGRES_DB: postgres
      POSTGRES_HOST: localhost:5432
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      AWS_BUCKET: udagram-bucket-1234567
      JWT_SECRET: testing
      URL: 'http://localhost:8100'

  udagram-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcd1234
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

networks:
  udagram: